FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine:latest
RUN apk --no-cache add ca-certificates docker-cli docker-cli-compose
WORKDIR /app
COPY --from=builder /app/server .

EXPOSE 8080
CMD ["./server"]
